apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-stack-tls
  namespace: elastic-stack
spec:
  secretName: elastic-stack-tls-secret # 证书将存储在这个 Secret 中
  issuerRef:
    name: selfsigned-issuer # 替换为你集群中的 ClusterIssuer 或 Issuer 名称
    kind: ClusterIssuer
  commonName: kibana.sumery.com
  dnsNames:
    - "es.sumery.com"
    - "kibana.sumery.com"
    - "kb.sumery.com"
