apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-vpa
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "30m"
          memory: "128Mi"
        maxAllowed:
          cpu: "300m"
          memory: "512Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jaeger-vpa
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaeger
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "50m"
          memory: "128Mi"
        maxAllowed:
          cpu: "400m"
          memory: "512Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kibana-vpa
  namespace: elastic-stack
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: es-kb-quickstart-eck-kibana-kb
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "100m"
          memory: "300Mi"
        maxAllowed:
          cpu: "600m"
          memory: "1Gi" # Kibana 是 Node.js 写的，比较吃内存，卡死 1G 上限
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kafka-ui-vpa
  namespace: kafka
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafbat-ui-kafka-ui
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "30m"
          memory: "128Mi"
        maxAllowed:
          cpu: "300m"
          memory: "512Mi"
