#!/bin/bash

set -x

mkdir -p /home/kubernetes/postgres
cd /home/kubernetes/postgres

#helm install postgres oci://registry-1.docker.io/bitnamicharts/postgresql

VERSION="18.5.16"
# https://artifacthub.io/packages/helm/bitnami/postgresql?modal=install

#wget https://charts.bitnami.com/bitnami/postgresql-${VERSION}.tgz
helm repo add bitnami https://charts.bitnami.com/bitnami
helm pull bitnami/postgresql --version $VERSION

#helm pull ingress-nginx/ingress-nginx --untar --untar-dir /path/to/directory

tar -zxvf postgresql-${VERSION}.tgz

# 根据你的 kubectl get sc 输出，你有几个选择。
# 对于 PostgreSQL，您应该使用提供高可用性和数据持久性的 StorageClass，
# 例如由 OpenEBS Mayastor 支持的 StorageClass。
# 如果您没有可用的 Mayastor StorageClass，您可以临时使用 openebs-lvmpv 进行测试，但它缺少数据复制。
# 假设你有一个合适的，比如 openebs-mayastor。把它的sc名称添加到primary.persistence.storageClassName=<sc-name>参数里
kubectl get sc

#cat > pg_hba-values.yml <<EOF
#primary:
#  configuration: |
#    listen_addresses = '*'
#    port = 5432
#    max_connections = 500
#    # ... 其他所有必要配置
#EOF

# https://artifacthub.io/packages/helm/bitnami/postgresql?modal=template&template=backup/cronjob.yaml
#cat > postgresql-conf-values.yml <<EOF
#primary:
#  extendedConfiguration: |
#    # WARNING
#    # wal_compression = lz4 requires PostgreSQL
#    # to be compiled with --with-lz4
#    # io_method = io_uring requires PostgreSQL
#    # to be compiled with --with-liburing
#
#    # DB Version: 18
#    # OS Type: linux
#    # DB Type: mixed
#    # Total Memory (RAM): 4 GB
#    # CPUs num: 2
#    # Connections num: 100
#    # Data Storage: nvme
#
#    max_connections = 100
#    shared_buffers = 1GB
#    effective_cache_size = 3GB
#    maintenance_work_mem = 256MB
#    checkpoint_completion_target = 0.9
#    wal_buffers = 16MB
#    default_statistics_target = 100
#    random_page_cost = 1.1
#    effective_io_concurrency = 1000
#    work_mem = 4854kB
#    huge_pages = off
#    jit = off
#    wal_compression = lz4
#    io_method = io_uring
#    min_wal_size = 1GB
#    max_wal_size = 4GB
#    timezone = 'Asia/Shanghai'
#EOF

cat  > postgresql.conf <<EOF
# WARNING
# wal_compression = lz4 requires PostgreSQL
# to be compiled with --with-lz4
# io_method = io_uring requires PostgreSQL
# to be compiled with --with-liburing

# DB Version: 18
# OS Type: linux
# DB Type: mixed
# Total Memory (RAM): 4 GB
# CPUs num: 2
# Connections num: 100
# Data Storage: nvme

timezone = 'Asia/Shanghai'
max_connections = 100
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 1000
work_mem = 4854kB
huge_pages = off
jit = off
wal_compression = lz4
io_method = io_uring
min_wal_size = 1GB
max_wal_size = 4GB
EOF

cat  > pg_hba.conf <<EOF
# TYPE  DATABASE        USER            ADDRESS                 METHOD
hostssl all             all             0.0.0.0/0               scram-sha-256
EOF

kubectl create configmap my-postgres-config \
  --from-file=postgresql.conf \
  --from-file=pg_hba.conf \
  -n postgres

# helm uninstall postgres -n postgres || true
helm upgrade --install postgres ./postgresql \
  -n postgres \
  --create-namespace \
  --set global.postgresql.auth.username="postgres" \
  --set global.postgresql.auth.password="msdnmm" \
  --set global.postgresql.auth.database="postgres" \
  --set primary.service.type=LoadBalancer \
  --set global.postgresql.service.ports.postgresql="5432" \
  --set primary.persistence.storageClass="openebs-lvmpv-postgres" \
  --set tls.enabled=false \
  --set volumePermissions.enabled=true \
  --set tls.tls.autoGenerated=false \
  --set tls.certificatesSecret="postgres-gateway-tls-secret" \
  --set tls.certFilename="tls.crt" \
  --set tls.certKeyFilename="tls.key" \
  --set primary.existingConfigmap="my-postgres-config"

set +x
