apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: postgres-route
  namespace: postgres
spec:
  parentRefs:
    - name: postgres-gateway
      sectionName: https # 对应 Gateway 的监听器名称
  hostnames:
    - "pg.sumery.com"
    - "postgres.sumery.com"
  rules:
    - backendRefs:
        - name: postgres-postgresql
          port: 5432
