apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: jaeger-grpc-route
  namespace: observability
spec:
  parentRefs:
    - name: observability-gateway
      sectionName: https
  hostnames:
    - "jaeger-grpc.sumery.com"
  rules:
    - backendRefs:
        - name: jaeger
          port: 4317
